#!/usr/bin/env -S deno run -A --ext=ts

if (Deno.args.length === 1 && Deno.args[0] === "manifest") {
  const manifest = {
    title: "Slides",
    commands: [
      {
        name: "show",
        title: "Show a slide",
        mode: "view",
        params: [
          {
            name: "path",
            type: "string",
          },
          {
            name: "index",
            type: "string",
            optional: true,
          },
        ],
      },
    ],
  };
  console.log(JSON.stringify(manifest));
  Deno.exit(0);
}

import { toJson } from "https://deno.land/std@0.203.0/streams/mod.ts";
const { command, params } = await toJson(Deno.stdin.readable) as {
  command: string, params: { [key: string]: any },
}

if (command == "show") {
  const markdown = Deno.readTextFileSync(params.path);

  const sections = markdown.split("\n---\n");

  const index = params.index || 0;
  const section = sections[index];

  const actions = [];
  if (index < sections.length - 1) {
    actions.push({
      title: "Next",
      key: "n",
      onAction: {
        type: "reload",
        params: {
          path: params.path,
          index: index + 1,
        },
      },
    });
  }
  if (index > 0) {
    actions.push({
      title: "Previous",
      key: "p",
      onAction: {
        type: "reload",
        params: {
          path: params.path,
          index: index - 1,
        },
      },
    });
  }

  const detail = {
    type: "detail",
    text: section.trim(),
    language: "markdown",
    actions: actions,
  };

  console.log(JSON.stringify(detail));
}
